version: '3'

services:
  fyle:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7755:7755"
    environment:
      - FLASK_APP=/usr/src/app/core/server.py
    volumes:
      - .:/usr/src/app